import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import Home from '../comp/Home';

const inter = Inter({ subsets: ['latin'] });

export default function Index() {
  return (
    <>
      <Head>
        <title>threejs demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.style}>
        <div id="mainWrapper">
          <Home />
        </div>
      </main>
    </>
  );
}
